// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPGD_9UczFcu9LrLUsPOnNpWaUobsOSw',
    appId: '1:900163496482:web:74cb9855974df8b814387b',
    messagingSenderId: '900163496482',
    projectId: 'fir-flutter-codelab-908ef',
    authDomain: 'fir-flutter-codelab-908ef.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-908ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvggEHzqnxSWUQkOvrDkOuVVnEFgLAoI0',
    appId: '1:900163496482:android:ea3a8ddcfcd67d8114387b',
    messagingSenderId: '900163496482',
    projectId: 'fir-flutter-codelab-908ef',
    storageBucket: 'fir-flutter-codelab-908ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7HQjopkWauechvN9NwtSHzxAlyzhZZM',
    appId: '1:900163496482:ios:81fb15f6063dac0a14387b',
    messagingSenderId: '900163496482',
    projectId: 'fir-flutter-codelab-908ef',
    storageBucket: 'fir-flutter-codelab-908ef.appspot.com',
    iosClientId: '900163496482-pm38m7jilu926hsadnt1eontm2pp39g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW7HQjopkWauechvN9NwtSHzxAlyzhZZM',
    appId: '1:900163496482:ios:81fb15f6063dac0a14387b',
    messagingSenderId: '900163496482',
    projectId: 'fir-flutter-codelab-908ef',
    storageBucket: 'fir-flutter-codelab-908ef.appspot.com',
    iosClientId: '900163496482-pm38m7jilu926hsadnt1eontm2pp39g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
